name: cs-181-final
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - ipykernel
  - jupyter
  - psutil
  - pyyaml
  - pip:
      - accelerate==1.6.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - attrs==25.3.0
      - datasets==3.5.0
      - dill==0.3.8
      - evaluate==0.4.3
      - frozenlist==1.6.0
      - fsspec==2024.12.0
      - hf-xet==1.0.4
      - huggingface-hub==0.30.2
      - multidict==6.4.3
      - multiprocess==0.70.16
      - pip==25.0.1
      - propcache==0.3.1
      - pyarrow==19.0.1
      - regex==2024.11.6
      - safetensors==0.5.3
      - sympy==1.13.1
      - tokenizers==0.21.1
      - tqdm==4.67.1
      - transformers==4.51.3
      - xxhash==3.5.0
      - yarl==1.20.0